version: "3"

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    # depends_on:
    #   - redis
    command: celery -A project.celery worker --pool=solo --loglevel=info	
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    depends_on:
      - redis
    command: celery -A project beat -l info
