# Generated by Django 4.1.7 on 2023-03-25 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
