# Generated by Django 4.1.7 on 2023-03-28 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_alter_room_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
