# Generated by Django 4.1.7 on 2023-04-03 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_alter_room_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(),
        ),
    ]
