# Generated by Django 4.1.7 on 2023-04-03 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_alter_room_discount_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
