# Generated by Django 4.1.7 on 2023-03-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_hotelimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Hotel.hotel'),
            preserve_default=False,
        ),
    ]
