# Generated by Django 4.1.7 on 2023-03-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_openinghour_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='hotel_name',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='instegram',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='twitter',
        ),
        migrations.CreateModel(
            name='HotelSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='Hotel.hotel')),
            ],
        ),
    ]
